module.exports = {
  User: require('./User'),
  Category: require('./Category'),
  Product: require('./Product'),
  Order: require('./Order'),
  Counter: require('./Counter'),
  Gallery: require('./Gallery'),
  Content: require('./Content'),
  ContactMessage: require('./ContactMessage'),
  BulkOrder: require('./BulkOrder'),
  Certification: require('./Certification'),
  StockLoss: require('./StockLoss'),
  Notification: require('./Notification'),
  MarketTrip: require('./MarketTrip'),
  StockMovement: require('./StockMovement'),
  FlockBatch: require('./FlockBatch'),
  FeedItem: require('./FeedItem'),
  FeedTransaction: require('./FeedTransaction'),
  MedicineItem: require('./MedicineItem'),
  MedicineTransaction: require('./MedicineTransaction'),
  ProcessingRun: require('./ProcessingRun'),
};
